### PR TITLE
fix: set explicit default value for `default_prefix_filter`

### LINKED ISSUE #699: Resource "ibm_tg_connection" uses an undocumented argument
Resource `ibm_tg_connection` in this module uses the [undocumented argument](https://registry.terraform.io/providers/IBM-Cloud/ibm/1.82.1/docs/resources/tg_connection#argument-reference) `default_prefix_filter` in [`main.tf`](https://github.com/terraform-ibm-modules/terraform-ibm-transit-gateway/blob/d9b8743c4df66e8e79b7e9bb3e1e57a726709779/main.tf#L23).
Related variable `vpc_connection` states the default value is `permit`, even though this value isn't handled by terraform configuration:
`    default_prefix_filter = optional(string)`
if handled by terraform should then be:
`    default_prefix_filter = optional(string, "permit")`
Does the API handle this default value? Why not pass the `permit` value as stated in the validation block?

### PR DESCRIPTION
**Pull request by iamar7**
### Description

Resolves: https://github.com/terraform-ibm-modules/terraform-ibm-transit-gateway/issues/699

- Updated `default_prefix_filter = optional(string, "permit")` instead of `default_prefix_filter = optional(string)`

- Removed invaled `null` value from `vpc_connections` and `directlink_connections`

- Since the transit gateway team has set a rate limiter so I've moved some of the tests from pr_tests to other_test to resolve the pipeline failures

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Default value set for the argument `default_prefix_filter` to permit for both `vpc_connections` and `directlink_connections` variables.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by Ak-sky — DISMISSED** [review]

**Comment by iamar7** [comment]
> Re-running the pipeline since the failure seems to be due to Multiple tests executing simultaneously

Confirmed by @vbontempi that the transit gateway team has set a rate limiter.

**Review by vbontempi — APPROVED** [review]

File: tests/other_test.go [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+	// t.Parallel()  // Remove parallel testing due to rate limiting set by transit gateway team
+
+	options := setupOptions2VpcsExample(t, "twovpcs-tg")
+
+	output, err := options.RunTestConsistency()
+	assert.Nil(t, err, "This should not have errored")
+	assert.NotNil(t, output, "Expected some output")
+}
+
+// func setupOptionsCrossaccountsExample(t *testing.T, prefix string) *testhelper.TestOptions {
```
Comment (Ak-sky) [inline tests/other_test.go:39]: Should have removed the commented code

Comment (iamar7) [reply tests/other_test.go:39]: Those were for testing crossaccount example since the account that this test was using has been removed so the test was disabled until we decide what account can be used
